apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: tpch-benchmark
  namespace: benchmark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 10.158.1.10:32000/spark-s3a:3.5.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://tpch-100/tpch-100-runner-all.py"

  sparkConf:
    "spark.hadoop.fs.s3a.endpoint":          "http://10.158.1.100:8000"
    "spark.hadoop.fs.s3a.access.key":        "admin"
    "spark.hadoop.fs.s3a.secret.key":        "lannion-enssat"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl":              "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.sql.shuffle.partitions":          "200"
    "spark.sql.adaptive.enabled":            "false"
    "spark.sql.optimizer.runtime.bloomFilter.enabled": "false"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.dynamicAllocation.enabled":                    "true"
    "spark.dynamicAllocation.minExecutors":               "5"
    "spark.dynamicAllocation.maxExecutors":               "50"
    "spark.dynamicAllocation.executorIdleTimeout":        "30s"
    "spark.dynamicAllocation.schedulerBacklogTimeout":    "5s"
    "spark.dynamicAllocation.shuffleTracking.enabled":    "true"
    "spark.dynamicAllocation.shuffleTracking.timeout":    "30min"

  restartPolicy:
    type: Never
  timeToLiveSeconds: 7200

  driver:
    cores: 2
    memory: "2g"
    serviceAccount: spark
    labels:
      benchmark: tpch

  executor:
    cores: 2
    memory: "2g"
    memoryOverhead: "2g"
    instances: 5
    labels:
      benchmark: tpch