---
- name: Install OpenJDK {{ java_version }}
  apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: present
  when: ansible_os_family == "Debian"

- name: Set JAVA_HOME in profile
  lineinfile:
    path: /etc/profile.d/java.sh
    create: yes
    line: "export JAVA_HOME=/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"
    state: present

- name: Verify Java installation
  command: java -version
  register: java_version_output
  changed_when: false